# 프로그램 오류

- 에러 또는 오류
  - 프로그램 실행 중 어떤 원인에 의해 오작동, 빚ㅇ사ㅇ적 종료되는 경우
  - 발생시점에 따라 `컴파일 에러` 와 `런타임 에러`로 나뉜다

  #### 컴파일 에러
   - 컴파일시 발생하는 에러

  #### 런타임 에러
   - 실행시 발생되는 에러
   - 실행시 발생하는 `에러`와 `예외`로 구분
   - 에러(Error)
    - 프로그램 코드에서 수습될 수 없는 심각한 오류
    - EX) 메모리 부족(OutOfMemoryError) , 스택오버플로우(StackOverflowError)
   - 예외(Exception)
    - 프로그램 코드에서 수습될 수 있는 다소 미약한 오류
  #### 논리적 에러
   - 실행은 되지만 의도와 다르게 동작하는것


### 예외 클래스 계층구조

Object클래스는 EXception과 Error클래스의 조상이다.


#### RuntimeExption

- 주로 프로그래머의 실수로 발생된다.
- EX) ArrayIndexOutOfBoundsException(배열범위 벗어남), NullPointerException(null 값인 참조변수 멤버호출)

#### Exception 

- 외부의 영향으로 발생할 수 있는 에러.
- 사용자의 실수같은 외적요인으로 인해 발생할 수 있음
- 존재하지 않는 파일 참조(FileNotFoundException), 클래스 이름 잘못적음(ClassNotFoundException), 입력 데이터 형식이 잘못됨(DataFormatExcetion)


![image](https://user-images.githubusercontent.com/78067072/221392905-5a36c657-91b6-49c1-9a4b-01dcb205f08b.png)


위와 같이 Excepetion 안에 Exception이 들어갈 경우Exception 스코프가 같으니 변수명은 다르게 처리한다.

해당 파일은 [Exception/ExceptionEx1.java] 에서 확인할 수 있다.




 [Exception/ExceptionEx1.java]: https://github.com/786khk/referenceBasic/edit/main/Exception/ExceptionEx1.java



아래와 같은 상황일 경우


![image](https://user-images.githubusercontent.com/78067072/221393725-08450d53-b366-4d18-b1b7-afed7b95df72.png)


연산시 0으로 나눌 수 없어 ArithmeticException이 발생한다.

물론 Math.random()으로 출력결과가 나오다 중단될 수 있다.


위의 코드를 바꿔보자면 아래와 같다

```java

public class ExceptionEx3 {
   
    public static void main(String[] args) {
        int num = 100;
        int result = 0;
    
        for (int i=0; i<10; i++){
            try {
                result = num/(int)( Math.random() * 10);
                System.out.println(result);
                
            } catch (Exception e) {

                System.out.println(0); // 에외일때만  0 출력한다.
               
            }
        }
    }
}

/*
11
14
25
20
0 // 예외
33
50
12
100
0 // 예외

*/


```


for문에서 try~catch를 해야 에러인 부분도 catch가 되어 정상종료가 된다.

해당 파일은  [Exception/ExceptionEx2.java]과  [Exception/ExceptionEx3.java]에서 확인할 수 있다.

 [Exception/ExceptionEx2.java]: https://github.com/786khk/referenceBasic/edit/main/Exception/ExceptionEx2.java
 [Exception/ExceptionEx3.java]: https://github.com/786khk/referenceBasic/edit/main/Exception/ExceptionEx3.java

### try~catch문의 흐름

#### try블럭 내 예외 발생할 경우
 - 일치하는 catch를 찾는다.
 - 일치하는 catch문을 수행한다. 그 다음 try~catch문을 빠져나와 가 다음문장을 계속 실행한다.
 - 일치하는 try catch가 없다면 예외처리가 되니지않음

#### try블럭 내 예외 발생하지 않는 경우
 - catch를 수행하디많고 전체 try~ catch문을 빠져나가 수행을 계속한다.


![image](https://user-images.githubusercontent.com/78067072/221394811-3862a5c2-0776-4728-b335-df9a74fe0700.png)


![image](https://user-images.githubusercontent.com/78067072/221394794-f27dde0b-6644-4b20-818e-22fcdbf128e5.png)
